WCS\XSSBundle\Entity\Sweet:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        price:
            type: float

    oneToMany:
        comments:
            targetEntity: Comment
            mappedBy: comments

    lifecycleCallbacks: {  }
