WCS\XSSBundle\Entity\User:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: 255

    oneToMany:
        comments:
            targetEntity: Comment
            mappedBy: comments

    lifecycleCallbacks: {  }
