sweet:
    path:     /
    defaults: { _controller: "WCSXSSBundle:Sweet:index" }

sweet_show:
    path:     /{id}/show
    defaults: { _controller: "WCSXSSBundle:Sweet:show" }

sweet_new:
    path:     /new
    defaults: { _controller: "WCSXSSBundle:Sweet:new" }

sweet_create:
    path:     /create
    defaults: { _controller: "WCSXSSBundle:Sweet:create" }
    requirements: { _method: post }

sweet_edit:
    path:     /{id}/edit
    defaults: { _controller: "WCSXSSBundle:Sweet:edit" }

sweet_update:
    path:     /{id}/update
    defaults: { _controller: "WCSXSSBundle:Sweet:update" }
    requirements: { _method: post|put }

sweet_delete:
    path:     /{id}/delete
    defaults: { _controller: "WCSXSSBundle:Sweet:delete" }
    requirements: { _method: post|delete }
